### ISSUE TITLE
Does X forwarding support every kind of GUI apps on Linux?

### ISSUE THREAD

**Issue by leimao** [justin-vanwinkle/Docker-XForward-Example#1]
Hello,

This is probably not an issue but a question. I heard that sometimes X forwarding will not work for some apps native. I wonder if we can just configure X forwarding properly so that every app with GUI on Linux, such as Slack, Sublime, and Evince, could be run without any problems. Thank you.

Best,

Lei

**Comment by justin-vanwinkle** [comment]
Hi Lei,

As far as I know, X forwarding should be completely functional for all applications in an X environment -- If I have a gap in knowledge here, please let me know and I will research a bit further.

Where it won't work is in a situation where you aren't running X Server on your host -- like if you are running Wayland or whatever Microsoft Windows runs.  This is because the X forward capability ends with the container -- the host has no way of interpreting and handling the signal it is receiving.  Although there are ways to work around this in both of the aforementioned compositors.

If you come across an application that won't work with X Forwarding, please let me know.  I'd be very interested to figure out why.

For what it's worth, I worked for several months with all of my GUI happening on one machine via X Forwarding and all of the compute happening on the originating machine.  I never came across a single application that was unusable.  Although it did get confusing when trying to figure out which machine a file saved to :laughing: 

Thanks,
Justin
